const appleSystemIndigo = '#5756CF';
const tint = appleSystemIndigo;
const tintInverse = 'white';

const colorModes = [
  {
    name: 'Light Mode',
    prefix: 'l',
    props: {
      '--l-tint': tint,
      '--l-tint-inverse': tintInverse,
      '--l-label': '#000',
      '--l-label-h': '0',
      '--l-label-s': '0%',
      '--l-label-l': '0%',
      '--l-label-a': '100%',
      '--l-secondary-label': '#3c3c439a',
      '--l-tertiary-label': '#3c3c434d',
      '--l-quaternary-label': '#3c3c432e',
      '--l-fill': '#78788033',
      '--l-fill-h': '240',
      '--l-fill-s': '3%',
      '--l-fill-l': '49%',
      '--l-fill-a': '16%',
      '--l-secondary-fill': '#78788029',
      '--l-secondary-fill-h': '240',
      '--l-secondary-fill-s': '3%',
      '--l-secondary-fill-l': '49%',
      '--l-secondary-fill-a': '20%',
      '--l-tertiary-fill': '#7676801f',
      '--l-quaternary-fill': '#74748014',
      '--l-placeholder-text': '',
      '--l-background': '#ffffff',
      '--l-secondary-background': '#f2f2f7',
      '--l-tertiary-background': '',
      '--l-grouped-background': '#f2f2f7',
      '--l-secondary-grouped-background': '#ffffff',
      '--l-tertiary-grouped-background': '#f2f2f7',
      '--l-separator': '#3c3c435c',
      '--l-opaque-separator': '#c6c6c8',
      '--l-link': tint,
      '--l-system-grey': '#8E8E93',
      '--l-system-grey2': '#AEAEB2',
      '--l-system-grey3': '#C7C7CC',
      '--l-system-grey4': '#D1D1D6',
      '--l-system-grey5': '#E5E5EA',
      '--l-system-grey6': '#F2F2F7',
      '--l-arbitrary-activity-indicator': '#80858E',
      '--l-animation-time-very-short': '0.05s',
      '--l-animation-time-short': '0.15s',
      '--l-animation-time-medium': '0.3s',
    },
  },
  {
    name: 'Dark Mode',
    prefix: 'd',
    props: {
      '--d-tint': tint,
      '--d-tint-inverse': tintInverse,
      '--d-label': '#ffffff',
      '--d-label-h': '0',
      '--d-label-s': '0%',
      '--d-label-l': '100%',
      '--d-label-a': '100%',
      '--d-secondary-label': '#ebebf59a',
      '--d-tertiary-label': '#ebebf54d',
      '--d-quaternary-label': '#ebebf52e',
      '--d-fill': '#7878805c',
      '--d-fill-h': '240',
      '--d-fill-s': '3%',
      '--d-fill-l': '49%',
      '--d-fill-a': '36%',
      '--d-secondary-fill': '#78788052',
      '--d-secondary-fill-h': '240',
      '--d-secondary-fill-s': '3%',
      '--d-secondary-fill-l': '49%',
      '--d-secondary-fill-a': '32%',
      '--d-tertiary-fill': '#7676803d',
      '--d-quaternary-fill': '#7474802e',
      '--d-placeholder-text': '',
      '--d-background': '#000000',
      '--d-secondary-background': '#1c1c1e',
      '--d-tertiary-background': '#2c2c2e',
      '--d-grouped-background': '#000000',
      '--d-secondary-grouped-background': '#1c1c1e',
      '--d-tertiary-grouped-background': '#2c2c2e',
      '--d-separator': '#545458a6',
      '--d-opaque-separator': '#38383a',
      '--d-link': tint,
      '--d-system-grey': '#8E8E93',
      '--d-system-grey2': '#636366',
      '--d-system-grey3': '#48484A',
      '--d-system-grey4': '#3A3A3C',
      '--d-system-grey5': '#2C2C2E',
      '--d-system-grey6': '#1C1C1E',
      '--d-arbitrary-activity-indicator': '#80858E',
      '--l-animation-time-very-short': '0.05s',
      '--d-animation-time-short': '0.15s',
      '--d-animation-time-medium': '0.3s',
    },
  },
];

export default colorModes;
